#!/bin/bash
# Written by Santiago Soler <santiago.r.soler@gmail.com> and
# Agustina Pesce <pesce.agustina@gmail.com>
# See https://www.github.com/aguspesce/aspect-docker for more information.
#
# Usage:
#   ./aspect-docker my-model.prm


# Define function to print usage help
function usage() {
	echo "Usage: $0 [-p PROCESSORS] <model-file>"
}


# --------------
# Read arguments
# --------------
MODEL_PATH=""
PROCESSORS=1

while [[ $# -gt 0 ]]; do
    argument=$1
    case $argument in
		-h|--help)
			usage && exit 0;;
        -p|--processors)
            PROCESSORS=$2
            shift  # past argument
            shift  # past value
            ;;
        *)  # ASPECT script filename
            MODEL_PATH=$1
            shift  # past script filename
            ;;
    esac
done

# Check if model filename has been passed as argument
if [ -z "$MODEL_PATH" ]; then
    usage && exit 0
fi

# Check if model filename exists
if [ ! -f "$MODEL_PATH" ]; then
    echo ERROR: Model file $MODEL_PATH not found
    exit
fi

# Define prefix for using mpirun in case the user wants to parallelize the run
PARALLEL_PREFIX=""
if [ $PROCESSORS -gt 1 ]; then
    PARALLEL_PREFIX="mpirun -np $PROCESSORS"
fi


# ----------------------------------------
# Define variables related to Docker image
# ----------------------------------------

# Docker image and tag
IMAGE=gassmoeller/aspect
TAG=latest

# Define HOME directory inside the container
GUEST_HOME=/home/dealii

# Path to aspect binary inside the container
ASPECT_DIR=$GUEST_HOME/aspect
ASPECT=$ASPECT_DIR/aspect

# Target where the host directory will be mounted
MOUNT_DIR=$ASPECT_DIR/model

# Get output directory from the .prm file
OUTPUT_DIR_NAME=$(grep -i "set Output directory" $MODEL_PATH | awk '{printf $NF}')

# Container name
CONTAINER_NAME=aspect_docker

# ----------
# Run ASPECT
# ----------
# Check if output dir exists on host
if [ -d $(pwd)/$OUTPUT_DIR_NAME ]; then
    echo "ERROR: Output directory $OUTPUT_DIR_NAME already exists."
    exit
fi

# Run an aspect container
docker run --name $CONTAINER_NAME -it --volume "$(pwd):$MOUNT_DIR:ro" $IMAGE:$TAG /bin/bash -c "$PARALLEL_PREFIX $ASPECT $MOUNT_DIR/$MODEL_PATH"

# Retrieve output directory from the container
docker cp $CONTAINER_NAME:$ASPECT_DIR/$OUTPUT_DIR_NAME .

# Remove the container because it's not longer needed
docker rm $CONTAINER_NAME
